# This rule is not used by the project developer-portal-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over devportal.kuadrant.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: developer-portal-controller
    app.kubernetes.io/managed-by: kustomize
  name: apikey-admin-role
rules:
- apiGroups:
  - devportal.kuadrant.io
  resources:
  - apikeys
  verbs:
  - '*'
- apiGroups:
  - devportal.kuadrant.io
  resources:
  - apikeys/status
  verbs:
  - get
