apiVersion: devportal.kuadrant.io/v1alpha1
kind: APIKey
metadata:
  labels:
    app.kubernetes.io/name: developer-portal-controller
    app.kubernetes.io/managed-by: kustomize
  name: toystore-apikey
spec:
  apiProductRef:
    name: toystore-api
  planTier: gold
  useCase: "Authentication key for our Toystore API"
  requestedBy:
    userId: user-12345
    email: developer@example.com
