apiVersion: devportal.kuadrant.io/v1alpha1
kind: APIProduct
metadata:
  labels:
    app.kubernetes.io/name: developer-portal-controller
    app.kubernetes.io/managed-by: kustomize
  name: apiproduct-sample
spec:
  # TODO(user): Add fields here
